#!/bin/bash
#
# Title:      rsync_backup docker with automatic  upload functionality 
# Author(s):  MrDoob / doob187 / kkhiller
#
# License:    Copyright (c) 2020 @Authors
# Own Risk any edits or mods 
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        g_role: 'rsync-backup'
        image: 'mrdoob/rsyncbackup:latest'

    - name: 'Register TimeZone'
      shell: 'cat /etc/timezone'
      register: tz
      
    - name: 'Setting {{g_role}} Volumes'
      set_fact:
        g_volumes:
          - '/opt/appdata/:/home'
          - '/mnt/backup:/backup'
          - '/opt/appdata/{{g_role}}/rclone:/rclone'
          - '/opt/appdata/{{g_role}}/log:/log'

    - name: 'Setting {{amg_role}} ENV'
      set_fact:
        g_env:
          CRON_TIME : '0 1 * * *'
          CONTAINER_TIMEZONE: '{{tz.stdout}}'

    ## VALUES for upload backups

    - name: 'Create Backup dir folder'
      file:
        path: '/mnt/backup/'
        state: directory
        mode: '0755'

    - name: 'Create {{g_role}} dir folder'
      file:
        path: '/opt/appdata/{{g_role}}/rclone'
        state: directory
        mode: '0755'

    - name: 'Check of Existance files in {{ g_role }}'
      stat:
        path: '/opt/appdata/{{g_role}}/rclone/rclone.conf'
      register: rcp

    - name: 'Remove old rclone.conf from {{ g_role }} folder'
      shell: 'rm -rf /opt/appdata/{{g_role}}/rclone/rclone.conf'
      ignore_errors: yes
      when: rcp.stat.exists == true

    - name: 'Clone rclone.config to {{ g_role }} folder' 
      shell: 'cp -r /opt/appdata/plexguide/rclone.conf /opt/appdata/{{g_role}}/rclone/rclone.conf'
      ignore_errors: yes

    # MAIN DEPLOYMENT
    # #############################################################
    - name: 'Deploying {{g_role}}'
      docker_container:
        name: '{{g_role}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{g_volumes}}'
        env: '{{g_env}}'
        capabilities:
          - 'SYS_TIME'
          - 'SYS_NICE'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - 'rsync-backup'
        state: started
